import {
  Box,
  Button,
  Flex,
  Link,
  Text,
  VStack
} from "@chakra-ui/react";
import { usePrivy } from "@privy-io/react-auth";
import Head from "next/head";
import Image from "next/image";
import NextLink from "next/link";
import * as GreenPillLogo from "../../public/svgPatterns/pattern-7.svg";
import site from "../config/site";


export const LandingLayout = ({ children }: any) => {
  return (
    <VStack minHeight="100vh">
      <Head>
        <title>{site.title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />
      
      {children}
      <Footer />
    </VStack>
  );
};

function Header() {
  return (
    <Flex
      as="nav"
      position={"absolute"}
      w={"full"}
      justifyContent="space-between"
      alignItems="center"
      textColor={"dark-green"}
      zIndex={10}
      backgroundColor={"transparent"}
      height={"5rem"}
      top={"0"}
    >
      <Link as={NextLink} href={"/"} variant="primary" textColor={"dark-green"}>
        <Image
          src={GreenPillLogo}
          alt="Green pill logo"
          width={"150"}
          height={"150"}
        />
      </Link>
      <PrivyAuthButton />
    </Flex>
  );
}

function Hero() {
  return (
    <Flex
      direction={"column"}
      justifyContent={"center"}
      alignItems={"flex-start"}
      textAlign={"left"}
      height={"32rem"}
      width={"full"}
      padding={"4rem"}
      backgroundColor={"green"}
      backgroundImage={"url(/svgPatterns/heroSvg.svg)"}
      backgroundSize={"auto"}
      backgroundPosition={"right"}
      backgroundRepeat={"no-repeat"}
      fontSize={"2xl"}
    >
      <Text fontSize={"6xl"} color={"dark-green"} fontWeight={"bold"}>
        Green Pill
      </Text>
      <Text color={"dark-green"}>A regenerative internet</Text>
      <Text color={"dark-green"}>Powered by the blockchain</Text>
      <Text color={"dark-green"}>Built by supermodular.xyz</Text>
    </Flex>
  );
}

const Footer = () => (
  <Flex
    as="footer"
    w={"full"}
    position={'absolute'}
    justifyContent="center"
    alignItems="center"
    textColor={"dark-green"}
    backgroundColor={"green"}
    height={"5rem"}
    bottom={"0"}
  >
    Learn More
  </Flex>
);

function PrivyAuthButton() {
  const { login, ready, authenticated, user, logout } = usePrivy();

  const address = user?.wallet?.address;
  if (!ready) return <Box>Loading...</Box>;

  if (authenticated)
    return (
      <Button
        onClick={logout}
        variant="secondary"
        marginRight="10px"
        width={"max-content"}
      >
        Logged in as{" "}
        {address?.substring(0, 4) +
          "..." +
          address?.substring(address?.length - 4)}
      </Button>
    );

  if (ready && !authenticated)
    return (
      <Button onClick={login} variant="secondary" marginRight="10px">
        Connect
      </Button>
    );
}